"""
Django settings for norpro_security project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fx3&*hduf)g7$r!^3_68085pm%0a5j%y=*-ov=tnhg)hie(qnv'

# SECURITY WARNING: don't run with debug turned on in production!

# local
DEBUG = True
ALLOWED_HOSTS = ["*"]
CRON_SECRET_KEY='237852ff1e90d6559e475939eed6c44e5e74da0572342386fb46f03bef0f3053'

# live
# DEBUG =False
# ALLOWED_HOSTS = ["norpro.ca", "*"]
# CRON_SECRET_KEY='237852ff1e90d6559e475939eed6c44e5e74da0572342386fb46f03bef0f3053'


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Add this
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'norpro_app',
    'taggit',
    'ckeditor',
    'ckeditor_uploader',
    'embed_video',
    'django_select2',
    'corsheaders',
    
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  
    'http://localhost:3001',
    'https://norpro-announcements-fe-nextjs.vercel.app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'norpro_security.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'norpro_security.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'norpro_app.authentication.CustomAuthentication',  # Use your custom authentication class
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}




# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Set token expiry (1 hour)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token expiry (7 days)
    'ROTATE_REFRESH_TOKENS': True,  # Issue new refresh token with access token
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh token after rotation
    'TOKEN_BLACKLIST': True,
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# local development

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'norpro_app/static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'norpro/media')
MEDIA_URL = '/media/'

# live deployment

# STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'norpro_app/static')]
# MEDIA_ROOT = os.path.join(BASE_DIR, 'norpro/media')
# MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# EMAIL_USE_SSL = True
# EMAIL_USE_TLS = False
# EMAIL_HOST = 'smtp.hostinger.com'
# EMAIL_PORT = 465
# EMAIL_HOST_USER = 'donotreply@norpro.ca'
# EMAIL_HOST_PASSWORD = 'M*030308477640uk'
# DEFAULT_FROM_EMAIL = 'NORPRO <donotreply@norpro.ca>'

#Test Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'abhinandtk.primalcodes@gmail.com'
EMAIL_HOST_PASSWORD = 'dgui dwwn iyar ycdv'  # Use App Password if using Gmail



# ///////ckeditor///////////


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_ALLOW_CONTENT = True
CKEDITOR_CONFIGS = {
    'default': {
        # 'toolbar': 'Custom',
        'allowedContent': True,
        'extraAllowedContent': 'iframe[!src, allowfullscreen, frameborder, allow-scripts]',
        # 'extraPlugins': 'youtube',
        # 'youtube_responsive': True,  # Enable responsive embeds for YouTube videos
        # 'width': 500,
        # 'toolbar_Custom': [
        #     ['Bold', 'Italic', 'Underline'],
        #     ['NumberedList', 'BulletedList'],
        # ],
    },
}

AUTH_USER_MODEL = 'norpro_app.AdminUser'